### ISSUE TITLE
PyCharm installation failed on Termux-x11 

### ISSUE THREAD

**Issue by chopin** [phoenixbyrd/Termux_XFCE#1]
Do you know how to install Pycharm on Termux-x11 (Android, Arm)?

I tried all versions released by Pycharm, but all failed due to java library problems. I am  not sure whether it is due to the OS (Debian by Termux_XFCE). Pycharm is running well in Termux Ubuntu using VNC.

Thanks in advance.

**Comment by phoenixbyrd** [comment]
I'm not sure. Never used pycharm before. When I tried installing and running I got this error

Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by chopin** [comment]
Thanks for your reply. And thanks for sharing Termux-x11. It installs x11 in my smartphone nicely including WebGpu in Firefox.  Before this, I had to spend a lot of time installing x11 in my phone and never succeded on WebGpu. 

By the way, have you tried any source code IDE other than Pycharom on Termux-x11? I am trying to see whether I can use Termux-x11 as my development environment (Galaxy DEX mode). 

Thanks again.

**Comment by phoenixbyrd** [comment]
I managed to get it to run ... sometimes ... idk what's wrong with it but most the time it just doesn't want to run and then for no apparent reason it just decides everything is fine and opens right up. Here's the install script if you want to test it out ...

#!/bin/bash

pkg install openjdk-17 -y
wget https://download.jetbrains.com/python/pycharm-community-2023.2-aarch64.tar.gz
tar -xvf pycharm-community-2023.2-aarch64.tar.gz
mv pycharm-community-2023.2 pycharm
cp $HOME/../usr/lib/libsqlite3.so $HOME/pycharm/lib/native/linux-aarch64/

echo "
alias pycharm='PYCHARM_JDK=/data/data/com.termux/files/usr/opt/openjdk $HOME/pycharm/bin/./pycharm.sh'
" >> $HOME/.bashrc

source $HOME/.bashrc

I haven't tried other IDE's other than vscode ... I don't know a lot about python so never really messed with IDEs for it. I've made a python app before, but I just used mousepad or nano to code it.

**Comment by romanovj** [comment]
you didn't replace pycharm-community-2023.2/lib/native/linux-aarch64/libsqliteij.so?

**Comment by phoenixbyrd** [comment]
Added PyCharm to the App Installer ... tested it a few times and seems to be working properly now on my end. Can you give it a try and let me know ... installs into debian proot, couldn't get it to play right on termux.

**Comment by chopin** [comment]
I just installed Pycharm by the App installer after I fixed --user to my id

[Edit Launcher]->[command] (by clicking on Pycharm icon on desktop):
... --user phoenixbyrd 
=> --user <my id>

Thank you so much for your help. I will take a look at Pycharm and post a comment about how it runs.

**Comment by phoenixbyrd** [comment]
Missed that! Thanks! Fixed the install script so it doesn't use my username now. Let me know how it works out.

**Comment by chopin** [comment]
I tested Pycharm, and it runs well in Termux-x11 so far. . Thank you so much for your help.

But there is still a big problem: Termux-x11 dies too often. I am not sure whether I can use Pycharm on Termux-x11 for my actual development.  I think that this issue is not specific to Pycharm, so I will open a new issue about it Thanks again..

**Comment by phoenixbyrd** [comment]
if it's signal 9 then follow this 
https://docs.andronix.app/android-12/andronix-on-android-12-and-beyond#install-adb
