### ISSUE TITLE
Visual Studio Code - Doesn't Launch

### ISSUE THREAD

**Issue by ccmscotland** [phoenixbyrd/Termux_XFCE#10]
Loving the XFCE Desktop running on my S23 Ultra - its incredible how well things work, great having an option of a proper "Desktop" Web Browser.
I'm struggling with Visual Studio Code though - I've installed it via the App Installer on the desktop and it seems to install, Icon appears on the desktop, etc but it never seems to launch when I try and load it - not sure if there's anything else I need to do to configure it?

**Comment by ccmscotland** [comment]
Attached a screenshot of the error I'm seeing in the Termux window when I try and launch 

![image](https://github.com/phoenixbyrd/Termux_XFCE/assets/79673402/2d2ddb5c-ba10-4eb6-acbf-f3679588d01e)

**Comment by phoenixbyrd** [comment]
possibly solved on discord, but still don't understand what happened. Will close issue here though.
