### ISSUE TITLE
[Feature Request] oh my zsh installer & custom resolv.conf file

### ISSUE THREAD

**Issue by doctor500** [phoenixbyrd/Termux_XFCE#11]
Hi @phoenixbyrd, 

Thanks for the excellent project here, really appreciate this idea from me who tried to make an Android workstation. As far as I tried this script I want to give some requests for increasing the script capabilities:

### Optional toggle to install [Oh my Zsh](https://wiki.termux.com/wiki/ZSH) 
For people who work a lot using terminals, these tools help us a lot because of the plugin provided by Omz. if you can change the bash to zsh it will be more standardized (most of my colleagues across the company use omz as well), but at least I hope there's an option like toggle or choice to choose either bash or oh my zsh during the installation process

### Custom `resolv.conf` options
For some reason, I have to edit `resolv.conf` to using proot, it is probably because of my home/office network setup. but, hope these options can be available in this script. currently, I need to manually edit the `setup.sh` script and add some hacky way to edit the resolv.conf file. this feature can be optional also, like if the user provides a custom resolv.conf file, they can able to override the stock `resolv.conf` with their own

Hope my request can be considered and make this project more awesome from time to time.
Thanks!

**Comment by phoenixbyrd** [comment]
I'm sorry, I'm part of the bash master race. I don't know anything about anything other than bash so I'll leave terminal customization up to each individual themselves if they don't like bash. Idk what changes need to be made to resolv.conf, also sounds like an issue that's based on individual needs.

**Comment by doctor500** [comment]
Thanks for the response! for zsh request, yeah sure no worries. maybe for resolv.conf let me take a look if there is a good approach that I can bring as MR or not
