### ISSUE TITLE
[Suggestion] use termux + android-tools to increase max_phantom_processes

### ISSUE THREAD

**Issue by crok** [phoenixbyrd/Termux_XFCE#15]
Hi,

In the "[Process completed (signal 9) - press Enter](https://github.com/phoenixbyrd/Termux_XFCE#process-completed-signal-9---press-enter)" section I would suggest to you to mention to use termux + android-tools to increase max_phantom_processes in the very same way you would use LADB (since termux is already in use and installing android-toold deb package is simpler (I think)).

Keep up the good work!

**Comment by phoenixbyrd** [comment]
idk how to do that, do you have instructions I can add?

**Comment by crok** [comment]
[termux](https://github.com/termux/termux-app#termux-application) - download from [GitHub](https://github.com/termux/termux-app/releases) or [F-Droid](https://f-droid.org/en/packages/com.termux/)
Upgrade your packages
`pkg upgrade`
then install android-tools package
`pkg install android-tools`
From now you have a functional adb and fastboot in your termux environment
and everything works just like you would do from a PC.
Connect the device to a WLAN (wireless debug can only be activated while you are connected to a WLAN)
Enable and open Developer options
Look for Wireless debug option and enable it.
In Wireless debug menu look for the Pair button and start it.
It will tell you the IP, port and PIN for pairing.
Open split screen with Wireless debug Pair menu and your termux.
Pair your termux adb with your phone using
`adb pair ip.ad.dr.ess:port_number`
something like `adb pair 192.168.0.150:37567`
It will ask for the PIN, after hitting enter the pairing is completed (it is a one-time activty).
Go back to the Wireless debug menu and check the IP and port for connection.
Now you can connect to your phone using:
`adb connect ip.ad.dr.ess:port_number`
something like `adb connect 192.168.0.150:37312`
It drops you to adb shell and you can do whatever you need or want to do.
When you finished just exit from the shell and disconncet your termux from the wireless debug with:
`adb disconnect`
Rarely adb stucks or having issues (like 'double connection', etc..)
so `adb killserver` command might be handy to know to start over..
[Here's a Youtube video on this - takes less than 2 mins (not mine but 100% accuarete).](https://www.youtube.com/watch?v=BHc7uvX34bM)

Or one can use [Shizuku and rish](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging) with [termux](https://www.youtube.com/watch?v=7mgZhCSdifc), too, that is easy to setup, too
(and [here's a 6 min video about it](https://www.youtube.com/watch?v=7mgZhCSdifc) - not mine but this is also 100% accurate).

**Comment by crok** [comment]
Great! Appreciate it. I would add a link to this issue as well, just in case.
