### ISSUE TITLE
Small keyboard issue...

### ISSUE THREAD

**Issue by CamsShaft** [phoenixbyrd/Termux_XFCE#17]
Hey man, this looks awesome so far, love it and thanks! I haven't got around to get an external keyboard yet because, well laziness... and the soft keyboard when I  close it I can't figure out for the life of me how to open it again. I'm not extremely well versed in using Linux and still learning so sometimes there's just way too much information in my head and get dyslexic. Also curious about installing other packages and running the icons from desktop, never had to configure anything from a terminal this way before. Sorry about the noob questions and thanks for any input! This will probably become a very popular android add on. BTW I'm using a Samsung galaxy S22 on Android 13.

UPDATE: After reading and trying to find a solution which didn't happen, the keyboard is still stuck and can't bring it up again. Also the xfce keyboard doesn't even load so I'm pretty confused and it's probably stupid and simple.

**Comment by phoenixbyrd** [comment]
termux-x11 will use the android system keyboard by pressing the android back button, although I highly recommend using this setup with a monitor and a bluetooth keyboard and mouse.

Installing packages is going to depend on what those packages are. ALL packages should be arm64 architecture. Pretty much all .deb's should be installed in the debian proot unless specifically built for termux. I've also included an app installer for additional stuff not found in the termux or debian repositories.

Please join the discord if you have an account, responses will be faster there.
