### ISSUE TITLE
How to copy and paste between Android and Termux X11?

### ISSUE THREAD

**Issue by chopin** [phoenixbyrd/Termux_XFCE#19]
Is there a way to copy and paste using clipboard between Android and  Termux X11?

**Comment by phoenixbyrd** [comment]
There is no solution other than pasting into a file and navigating to that file from within termux and copy/pasting from there. For some reason only copying from termux to android has been implemented in termux-x11. You'd have to talk to the dev on why that is.

**Comment by chopin** [comment]
I found that using Google Chat was pretty good to send messages to copy and paste text between different environments including mobile and browser.
