### ISSUE TITLE
How to increase stability of Termux-x11?

### ISSUE THREAD

**Issue by chopin** [phoenixbyrd/Termux_XFCE#2]
Hi again.

Thanks for phoenixbyrd's sharing of beautiful works, Termux-XFCE, I am happy to play with  Pycharm on X11 in my smartphone (Dex mode). I am dreaming about freedom from VNC nightmar,e and from headache managing a Windows laptop to use Web browser DevTool. My dream is to use only my smartphone for developing web applications

But, I found that Termux-x11 died too often, and I am having questions about whether it is too early to use it for my development environment. because Termux-x11 is still in an early alpha stage. So, I have questions to understand better about the stability of Termux-x11, and better ways to use it. Please share your experience with me and other people. I will add my experices too.

1. How often and when does Termux-x11 die?

In my case, it dies pretty often. Sometimes less than 1 minute, and sometimes in 10 minutes. However, It doesn't die pretty long time when I leave it behind but dies eventually.

2. When does Termux-x11 dies? Which program does kill it  more often?

It seems that Termux-x11 dies when I run something heavy. It doesn't look like a memory problem, but crashes on certain task or library. Firefox kills it pretty often. But WebGpu seems ok.

3. Does your Termux die too when Termux-x11 dies? 

Yes, my Termux dies too when Termux-x11 dies. I tried to use Tmux to avoid Termux crashing, but Tmux dies too when Termux-x11 dies. I think that the "start" command launches Termux-x11 as background process, and I don't understand why Termux dies when Termux-x11 dies.

4. Do you have some tips or ideas how to avoid Termux-x11 crash, and how to increase the stability of it?

I am thinking about avoiding using Firefox, and using Chromium instead.

To phoenixbyrd: Can you please update Chromium to the App install? Or please tell me how I can add Chromium on the App install.

Thanks again.

**Comment by phoenixbyrd** [comment]
I daily drive my Galaxy Fold 3, after fixing the process killer issue I haven't had it die on me or crash since. I don't think it's a Termux-X11 issue, it'll happen on vnc too. You can run vncstart to start the vncserver though and try.

**Comment by chopin** [comment]
> If this is a signal 9 issue then follow this
> 
> https://docs.andronix.app/android-12/andronix-on-android-12-and-beyond

Yes, it was signal 9, and I followed the webpage you commented. And, my Termux-x11 has not died so far. I am testing it running Firefox opening many webpages, and it is not dying anymore. It seems like the problem solved!

Now, my dream about using only a smartphone for developing applications has come true!. I don't need a desktop! I don't need a laptop!. Goodbye Vnc!  I feel like a new era of personal computing industry started. I am pretty sure that smartphones will kill desktops and laptops for most people..

Thank you so much for helping me out!

**Comment by phoenixbyrd** [comment]
Yea, been using my phones as my main device since the Note 9 with Dex. Took a break for a bit and used the Raspberry Pi, and now been using my Galaxy Fold 3 as my main pc since I got it. Things like GeForce Now and Magic DosBox are essential for gaming ... there's also shadow pc for thins that won't run on either of those.

**Comment by phoenixbyrd** [comment]
Honestly ... I wouldn't consider myself a developer or very knowledgeable. I've been learning as I go and fixing issues that I find or that others point out. If I get really really really stuck and google is no help then I use ChatGPT, especially for coding/scripting things or to have certain concepts explained so I can better understand what I'm looking at or doing at the moment. Mostly failed at this thing but I think it's working for most people now ... finally. At least complaints are getting less and what complaints there seems to be aren't directly related to anything I've done and seem to be more device specific which I can't resolve.
