### ISSUE TITLE
Scroll & Text Selection like Desktop 

### ISSUE THREAD

**Issue by ilkersigirci** [phoenixbyrd/Termux_XFCE#20]
Firstly, thanks for these scripts. They are the best for bringing linux on my Tab S9 Ultra. I am using my tablet with an official keyboard cover, and I wonder whether rit is possible to get a desktop-like scroll and text selection with the keyboard touchpad.

**Comment by phoenixbyrd** [comment]
I would assume so, never tried though since I don't really use keyboard stuff like that. Give it a try and see if it works.

**Comment by ilkersigirci** [comment]
Actually, I have tried and it didn't work like desktop. Anyway, thanks
