### ISSUE TITLE
ERROR: Failed to setup XFCE on Termux.

### ISSUE THREAD

**Issue by elvisisvan** [phoenixbyrd/Termux_XFCE#27]
i ran this command `curl -sL https://raw.githubusercontent.com/phoenixbyrd/Termux_XFCE/main/setup.sh -o setup.sh && chmod +x setup.sh && ./setup.sh`, proot-distro installed debian successfully, the process run for about 5 minutes and stopped with this error:
```
...
Preparing to unpack .../270-zstd_1.5.4+dfsg2-5_arm64.deb ... 
Unpacking zstd (1.5.4+dfsg2-5)...
Errors were encountered while processing:
/tmp/apt-dpkg-install-1JUEwx/022-liblerc4_4.0.0+ds-2_arm64.deb 
/tmp/apt-dpkg-install-1JUEwx/160-libdrm-radeon1_2.4.114-1+b1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: Failed to setup XFCE on Termux.
Please refer to the error message(s) above
```

what should i do?

**Comment by Waldo-ayy** [comment]
Same problem here.

**Comment by elvisisvan** [comment]
> Same problem here.

i backed termux environment up then uninstalled+reinstalled termux and the problem gone

**Comment by elvisisvan** [comment]
i fixed it, uninstall+reinstall termux the problem gone

**Comment by Waldo-ayy** [comment]
> i fixed it, uninstall+reinstall termux the problem gone

Actually I found out the reason. I was naming the user "root" and it caused a problem with proot. Proot started thinking the device was rooted and activated it's protections, blocking the script from using pkg.

Hope it might help anybody who has the same problem.
