### ISSUE TITLE
Termux is crashing after a while with errors

### ISSUE THREAD

**Issue by Iskose** [phoenixbyrd/Termux_XFCE#28]
While using it, after brief of time, it is crashing.

- I used directly your installer
- Samsung tab s9 plus
- Removed battery saver on termux
- screenshot attached
- 
![Screenshot_20240102_215005_Termux](https://github.com/phoenixbyrd/Termux_XFCE/assets/155398701/1aaa81ef-d25a-41f8-bd74-101ce631f152)

**Comment by bonecold24** [comment]
Signal 9 error read the readme again. There is also a youtube video link that solves the issue
