### ISSUE TITLE
I don't know how to install, confused.

### ISSUE THREAD

**Issue by Comy112** [phoenixbyrd/Termux_XFCE#3]
Hello. I am trying to install and after pasting in command in Termux which I am supposed to do for installation, I am confused on what should I do. I was greeted with options on screen and what should I do?
All I need Termux for is to run certain applications, and that's it.

**Comment by phoenixbyrd** [comment]
The github page and the end of the install process all explain what to do ... run start to open to the xfce desktop. 

This project is mostly geared for those who want as close to a full linux desktop environment and feel as possibly allowed by termux. I daily drive my Galaxy Fold 3 and this is my personal setup, I use this as a PC replacement. 

What specific use are you looking for, what certain apps?

**Comment by Comy112** [comment]
its mostly for testing, yeah.
