### ISSUE TITLE
Audio Issues on the XFCE

### ISSUE THREAD

**Issue by LmTechyTEM** [phoenixbyrd/Termux_XFCE#34]
HI I have a issue regarding the XFCE.Everything is now using dummy output and for some reaosn using pv actually allows me to hear audio from it I have no idea whats goig on.

**Comment by phoenixbyrd** [comment]
I'm not sure what you're asking or the issue

**Comment by EnoughIsAhnaf** [comment]
Hello, I am also having the same issue here. No audio is being outputted from my Galaxy Tab S9. It just lists my output device as a dummy output.

**Comment by EnoughIsAhnaf** [comment]
I managed to get audio output thanks to this thread: https://github.com/termux/termux-packages/issues/19623
I ran "nano ../usr/etc/bash.bashrc" and then at the very end added this line "pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1"
