### ISSUE TITLE
Vscode doesnt open

### ISSUE THREAD

**Issue by Alex460k** [phoenixbyrd/Termux_XFCE#38]
Please help me i really need to know how to open vscode. I did everything you sayd and it didnt work. I also wrote after ,, --no-sandbox '' --user-data-dir ( bc it worked in other distros )

**Comment by phoenixbyrd** [comment]
I've reinstalled everything and vscode opened for me with no issues. I'd need an error code to know what's going on.

**Comment by Alex460k** [comment]
It works now
