### ISSUE TITLE
How do I change the locale and keyboard language of my xfce desktop?

### ISSUE THREAD

**Issue by hansm629** [phoenixbyrd/Termux_XFCE#39]
@phoenixbyrd 
Thanks to you, I am now able to run the `PRoot Linux program` in a `Termux native xfce environment`. I am very grateful!

I have two questions.

**1. Inquiry on how to change xfce desktop locale**
I want to change the xfce desktop locale to `ko_KR_UTF-8`. How can I do that?

**2. Inquiry on how to set the USB keyboard language change key**
After adding `korean` to xfce's keyboard settings, I want to set the language `English <-> Korean` switching key to the `right Alt`, but it doesn't seem to apply. What should I do?

Please check~ :)

**Comment by phoenixbyrd** [comment]
I'm not sure how to do any of that.
