### ISSUE TITLE
Why???

### ISSUE THREAD

**Issue by SalehObb** [phoenixbyrd/Termux_XFCE#42]
![Screenshot_20240418_082510_Termux](https://github.com/phoenixbyrd/Termux_XFCE/assets/99651552/ab184aac-30e6-4cda-a5f0-2cf8f7769c68)
I dont get that what is the problem??

**Comment by phoenixbyrd** [comment]
I'm not exactly sure what's going  on there either. First time I've ever seen that error message. Are you using a VPN or something? Maybe a hiccup with your internet connection? I'm not well versed on connection issues so I can't really give a reasonable answer.

**Comment by SalehObb** [comment]
1. Not using vpn
2. Internet speed is 1020 kB
3. I even restart my phone and re installed termux

**Comment by phoenixbyrd** [comment]
I'm really not sure how to resolve this issue on your end, everything works fine on my side and everything I can find on this error seems to point to an internet connection issue which is out of my hands.

**Comment by SalehObb** [comment]
That just confusing 
I guess I'll just keep trying

**Comment by sabamdarif** [comment]
> That just confusing I guess I'll just keep trying

i think it's the problem of termux not the script 
i recommend you to first change termux repo mirror using **_termux-change-repo_** command then select a repo mirror (_alibaba open source mirror_ is always best for me)  update and upgrade termux once then try again

**Comment by phoenixbyrd** [comment]
The script actually prompts you to do this right after picking your username. Are you using termux from github/fdroid or playstore? Playstore version is no good, can't use that one.

**Comment by SalehObb** [comment]
This problem is just confusing i dont really understand it ,
But anyway i run the script again and it worked (i dont know how)
