### ISSUE TITLE
Visual Studio Code cannot be opened

### ISSUE THREAD

**Issue by LeftandRights** [phoenixbyrd/Termux_XFCE#5]
No response after installing and opening it from App Installer, same to the Webcord

**Comment by phoenixbyrd** [comment]
Try reinstalling the whole os, seems a change I was experimenting with broke something. Clear termux cache and data before resintalling

**Comment by LeftandRights** [comment]
> Try reinstalling the whole os, seems a change I was experimenting with broke something. Clear termux cache and data before reinstalling, let me know if it works.

Yeah i just did it, still the same.

**Comment by phoenixbyrd** [comment]
Give it another try, someone else just tried and it was working for them. Only issue I'm at right now is proot stuff isn't working in vncserver.

**Comment by phoenixbyrd** [comment]
closing this since no further communication
