### ISSUE TITLE
Layout design after neofetch command in terminal

### ISSUE THREAD

**Issue by hansm629** [phoenixbyrd/Termux_XFCE#50]
@phoenixbyrd 

I recently reinstalled Termux XFCE4.
When entering the neofetch command

![Screenshot_2024-06-01_19-07-58](https://github.com/phoenixbyrd/Termux_XFCE/assets/101167173/fd6ac78f-9fba-44c1-ae59-2e934755d4fc)

The layout design is displayed as default.
proot is displayed properly in Debian.

Even if I reinstall it, it's the same.

![Untitled](https://github.com/phoenixbyrd/Termux_XFCE/assets/101167173/d69550b6-fd1e-49f2-aa1b-aad09b8f8537)

What should I do to make it come out like this again?

**Comment by YuusaaZ** [comment]
That's indeed the case from the neofetch, it can't be changed because it's native termux-x11, if you want to change it try to change it in the neofetch config, the configuration file name is 'config.conf' I don't know what directory the configuration file is located in
