### ISSUE TITLE
How can I run a web server in 80(http) or 443(https) port?

### ISSUE THREAD

**Issue by warrenchopin** [phoenixbyrd/Termux_XFCE#53]
Hi,

I am trying to run a web server at port 80(http), or 443(https) in my device with Termux_XFCE. I have to do debugging in https because one of my libraries supports only https.

When I tried to launch a web server, I encountered an error: "Permission Denied" at socket open command at port 80.

(Node) http-server:
```
> http-server -p 80
node:events:497
Error: listen EACCES: permission denied 0.0.0.0:80
```
(Python) Tornado web server:
```
Running server <class 'tornado.web.Application'> at port 80
Traceback (most recent call last):
File "/home/.../venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/home/.../venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
PermissionError: [Errno 13] Permission denied
```
After searching the Internet, I found that ports below 1024 need root privileges in Linux/Unix ('sudo' cammand should be used).

So, I tried to run adding 'sudo'. But, I got the same error in case of Tornado server (Python). 

In case of (Node)http-server, 'sudo' command loses directory path failing finding files and raises an error:
```
> sudo /data/data/com.termux/files/usr/bin/http-server -p 80
/usr/bin/env: ‘node’: No such file or directory
```
I am wondering whether I need a complete root account to launch a web server. But, how can I?

Is there anyone who succeeded to launch a web server in Termux_XFCE?

I really appreciate your help.

**Comment by phoenixbyrd** [comment]
Use port 8080

**Comment by warrenchopin** [comment]
> Use port 8080

I cannot use port 8080 because I am using a networking library supporting only 443 port(https) which is using a public server for networking.

I am developing a web application supporting p2p communication between visitors. This web application includes the p2p library supporting only https(443 port) connections. 

So, I have to develop on a device running https server using 443 port. Is it not possible in Termux_XFCE?

Thanks again.

**Comment by warrenchopin** [comment]
I found that 8443 port can be used instead of 443  for SSL https web server. I successfully launched https web server on 8443 port in my device.   The problem solved.

Thanks.
