### ISSUE TITLE
Unable to correct problems, you have held broken packages. ERROR: Failed to setup XFCE on Termux.

### ISSUE THREAD

**Issue by Danielperfull-00** [phoenixbyrd/Termux_XFCE#55]
![image](https://github.com/user-attachments/assets/3ca01c5d-7a1e-45dc-97d1-d152a3cebb3b)

Me da ese error en susystem android en Fydeos 18

**Comment by YuusaaZ** [comment]
try reinstalling it, or read [this](https://github.com/phoenixbyrd/Termux_XFCE/issues/27) same problem but solved
