### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by RubixYouTube** [phoenixbyrd/Termux_XFCE#64]
The install has been failed, I tested it and it failure.

**Comment by RubixYouTube** [comment]
@phoenixbyrd the only think that can solve this issue is updating your scripts to the latest version
it was on the past.

**Comment by RubixYouTube** [comment]
by updating all bash (or all of your scripts (this option is optional)). @phoenixbyrd

**Comment by phoenixbyrd** [comment]
Update _what_ specifically? Without an error I don't know _what_ is wrong. It's not the entire script, there is a specific error and I'd like to know what that is so I know where it's failing for you. I can't fix an "it didn't work" issue without knowing anything.

**Comment by RubixYouTube** [comment]
@phoenixbyrd the install script., to update it to the latest version., so is the other bash scripts

**Comment by RubixYouTube** [comment]
so see you @phoenixbyrd !

**Comment by phoenixbyrd** [comment]
> @phoenixbyrd the install script., to update it to the latest version., so is the other bash scripts

Update _what_ to the latest version? I need to know _what_ specifically you are having an issue with. **Be Specific please!**

**Comment by RubixYouTube** [comment]
the "install.sh" because it's not updated in 5 months., please, update your
script., to install the latest debian version.

**Comment by phoenixbyrd** [comment]
ok nvm, I'm not gonna get the info I need from you.
