### ISSUE TITLE
How to install FileZilla

### ISSUE THREAD

**Issue by HasanAlyazidi** [phoenixbyrd/Termux_XFCE#66]
Hello,

Thank you for the awesome work.

How can I install software like FileZilla? i tired multiple ways with no avail.

Thank you.

**Comment by phoenixbyrd** [comment]
idk, couldn't tell you. I don't use it and don't know if there's even an aarch64 linux binary. If there isn't and it's not in either termux or debian proot repo then there isn't a way to install it.

**Comment by warrenchopin** [comment]
I use rsync instead FileZilla. I found that rsync was simpler and easier than FileZilla.
