### ISSUE TITLE
Unable to run any hadrware accelerated programs

### ISSUE THREAD

**Issue by parkerlreed** [phoenixbyrd/Termux_XFCE#69]
Using a Z Flip 3 with Snapdragon 888 5G and Adreno 660 on Android 14

Any time I try to run anything with Termux/Debian with zrun/zink I get this error

```
MESA: error: Zink vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
glx: failed to create drive screen
failed to load driver: zink
Error: couldn't get an RGB, Double-buffered visual
```

I was under the assumption this should work for Snapdragon CPU/GPU. Is this not the case?

**Comment by parkerlreed** [comment]
I see your Fold 3 has the same CPU and GPU so this is really confusing.

**Comment by phoenixbyrd** [comment]
Termux/Samsung broke things, still trying to figure everything out. I'm not a linux guru so who know's if I'll get it any time soon.

**Comment by parkerlreed** [comment]
Ahh thanks. I noticed I had to enable aaudio since Samsung's 6.1 update broke pulse as well, so not totally unexpected.
