### ISSUE TITLE
X11 server won't start.

### ISSUE THREAD

**Issue by Comy112** [phoenixbyrd/Termux_XFCE#7]
Hello, after the installation, X11 server do not want to start for some reason. I am not in proot, do I have to be in proot to start X11 server?
![Screenshot_20230827_162938_Termux](https://github.com/phoenixbyrd/Termux_XFCE/assets/102830774/1ea617f8-fa75-4486-a412-e9708658c2bf)

**Comment by phoenixbyrd** [comment]
Interesting! I'm not 100% sure, but looks like it's getting killed as soon as it starts. What's your device and specs? Might have to clear data and reinstall and this should be done in termux only, definitely not in proot. 

Another note, make sure termux-x11 app is installed and make sure termux is install from github or fdroid.

You can try editing the start script too ```nano ..usr/bin/start``` copy the below and replace what's in start with this. should get a bit more output, maybe something will help further figure this out.

#!/bin/bash

termux-x11 :1.0 &
#virgl_test_server_android --angle-gl & > /dev/null 2>&1
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity #> /dev/null 2>&1
env DISPLAY=:1.0 dbus-launch --exit-with-session glxfce & #> /dev/null 2>&1

sleep 5
process_id=$(ps -aux | grep '[x]fce4-screensaver' | awk '{print $2}')
kill "$process_id"

**Comment by Comy112** [comment]
device: Galaxy A12 Nacho
specs:
Exynos 850, Mali-G52, 6gb RAM
I have disabled phantom killer like last year, so it dont makes problems
I will try what you have said and let you know if it does in fact work. Thank you!

**Comment by Comy112** [comment]
Damn. I may have to reinstall because of this 
![Screenshot_20230827_213422_Termux](https://github.com/phoenixbyrd/Termux_XFCE/assets/102830774/b308ad22-235b-4476-bf6f-c49524b11b3b)

**Comment by phoenixbyrd** [comment]
> Damn. I may have to reinstall because of this ![Screenshot_20230827_213422_Termux](https://user-images.githubusercontent.com/102830774/263550238-b308ad22-235b-4476-bf6f-c49524b11b3b.jpg)

Sorry, had a typo...

```nano ../usr/bin/start```

**Comment by Comy112** [comment]
ah, alright, thank you

**Comment by Comy112** [comment]
It already has been in that. What should I do now?
![Screenshot_20230827_221455_Termux](https://github.com/phoenixbyrd/Termux_XFCE/assets/102830774/7c9ec049-061f-48d4-82d1-f4bca5420c5e)

**Comment by phoenixbyrd** [comment]
Just delete everything in start and copy/paste the other thing or comment out the lines manually like I have in the reply

**Comment by Comy112** [comment]
I managed to fix the issue by updating X11 app. Thank you for your help btw.

**Comment by phoenixbyrd** [comment]
I'll close out this issue since it's resolved now
