### ISSUE TITLE
How do I exit the program?

### ISSUE THREAD

**Issue by ionarevamp** [phoenixbyrd/Termux_XFCE#73]
After running `start`, I cannot seem to stop the proot instance nor the xfce4 session, even after exiting the terminal session. I was able to stop the display from showing up after running `killall --signal HUP dbus-launch` and killing the proot and xfce4 stuff - manually, but I don't want to have to do that every time. I tend to keep stuff in other tabs on backlog for easy access later so I don't want to have to exit Termux entirely every single time. For now I guess I'll have to edit the start command manually.

EDIT: It turns out that the kill_termux_x11 shortcut was just not properly installed somehow, so I had to do so myself

EDIT: Using the shortcut does exit termux:x11 BUT it crashes termux as well. Is there something I'm doing wrong?

**Comment by phoenixbyrd** [comment]
the script to shutdown intentionally closes termux ... I would like for it to close termux-x11 android app as well but haven't been able to figure out how yet.
