### ISSUE TITLE
Request to Add PRoot-Distro Ubuntu Selection Option

### ISSUE THREAD

**Issue by hansm629** [phoenixbyrd/Termux_XFCE#74]
Hello, Sir,

I’m finding this solution incredibly useful.

Would it be possible to add an option to select `PRoot-Distro Ubuntu` in addition to `PRoot-Distro Debian` during the installation process?

The versions of packages provided in `Debian 12` are often lower than those in `Ubuntu 24`, so using Ubuntu might be more convenient.

**Comment by phoenixbyrd** [comment]
I personally won't be doing that but feel free to fork this if you'd like. I'm not a fan of ubuntu.
