### ISSUE TITLE
Error en el ChromeOS

### ISSUE THREAD

**Issue by Danielperfull-00** [phoenixbyrd/Termux_XFCE#75]
![image](https://github.com/user-attachments/assets/7bffcf4d-d87a-4488-9fec-499d8eb0e2e4)

**Comment by phoenixbyrd** [comment]
If you're using the playstore version, uninstall it and reinstall using one from github.

**Comment by Danielperfull-00** [comment]
> If you're using the playstore version, uninstall it and reinstall using one from github.

I'm using the F-Droid version

**Comment by phoenixbyrd** [comment]
try uninstalling and reinstalling with github version.

**Comment by Danielperfull-00** [comment]
> Intente desinstalarlo y reinstalarlo con la versión de Github.

Not working, But I was able to put it in by starting the files manually and it worked
