### ISSUE TITLE
Shell command for ubuntu install is faulty

### ISSUE THREAD

**Issue by exsilium** [phoenixbyrd/Termux_XFCE#8]
Hi, noticed an error in the proposed Ubuntu install:

`curl -sL https://raw.githubusercontent.com/phoenixbyrd/Termux_XFCE/main/setup_ubuntu.sh -o setup_ubuntu.sh && chmod +x setup_ubuntu.sh && ./setup.sh`

The final command should call `./setup_ubuntu.sh` instead.

**Comment by phoenixbyrd** [comment]
Thanks! I missed that one.
